name: CI/CD for FastAPI Transformer

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Install dependencies (for tests, linting)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Optional: run tests
      - name: Run unit tests
        run: |
          pytest || echo "⚠️ No tests found, skipping"

      # Build Docker image
      - name: Build Docker image
        run: docker build -t fastapi-transformer .

      # Push image to Docker Hub (optional)
      - name: Log in to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag fastapi-transformer ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-transformer:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-transformer:latest

      # Deploy to Render via API (recommended)
      - name: Deploy to Render
        if: github.ref == 'refs/heads/main'
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          curl -X POST "https://api.render.com/v1/services/$SERVICE_ID/deploys" \
               -H "Authorization: Bearer $RENDER_API_KEY" \
               -H "Accept: application/json" \
               -d ''
